--
-- PostgreSQL database dump
--

\restrict UK363JKU4FCQ9ahdDhS8d4z8y0VvybM1Fqo1oR01G1aDjaPUfplwMQQqndXsUbp

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: api_alternative; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_alternative (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    image character varying(100),
    is_correct boolean NOT NULL,
    "order" integer NOT NULL,
    question_id bigint NOT NULL,
    CONSTRAINT api_alternative_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.api_alternative OWNER TO postgres;

--
-- Name: api_alternative_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_alternative ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_alternative_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_gamesession; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_gamesession (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    current_player_session_id bigint,
    alternatives_status boolean NOT NULL,
    gc_question_status boolean NOT NULL
);


ALTER TABLE public.api_gamesession OWNER TO postgres;

--
-- Name: api_gamesession_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_gamesession ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_gamesession_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_player; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_player (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    "order" integer NOT NULL,
    description text,
    CONSTRAINT api_player_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.api_player OWNER TO postgres;

--
-- Name: api_player_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_player ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_player_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_playerquestionanswer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_playerquestionanswer (
    id bigint NOT NULL,
    status character varying(20) NOT NULL,
    answered_at timestamp with time zone,
    selected_alternative_id bigint,
    player_session_id bigint NOT NULL,
    question_id bigint NOT NULL
);


ALTER TABLE public.api_playerquestionanswer OWNER TO postgres;

--
-- Name: api_playerquestionanswer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_playerquestionanswer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_playerquestionanswer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_playersession; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_playersession (
    id bigint NOT NULL,
    time_limit_seconds integer NOT NULL,
    accumulated_seconds integer NOT NULL,
    timer_status character varying(20) NOT NULL,
    last_timer_start timestamp with time zone,
    current_question_index integer NOT NULL,
    "order" integer NOT NULL,
    game_session_id bigint NOT NULL,
    player_id bigint NOT NULL,
    question_group_id bigint NOT NULL,
    alternative_text_visibility boolean NOT NULL,
    CONSTRAINT api_playersession_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.api_playersession OWNER TO postgres;

--
-- Name: api_playersession_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_playersession ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_playersession_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_question; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_question (
    id bigint NOT NULL,
    question_text text NOT NULL,
    "order" integer NOT NULL,
    question_group_id bigint NOT NULL,
    difficulty character varying(20) NOT NULL,
    CONSTRAINT api_question_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.api_question OWNER TO postgres;

--
-- Name: api_question_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_question ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_questiongroup; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_questiongroup (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    description text,
    created_at timestamp with time zone NOT NULL,
    "order" integer NOT NULL,
    CONSTRAINT api_questiongroup_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.api_questiongroup OWNER TO postgres;

--
-- Name: api_questiongroup_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_questiongroup ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_questiongroup_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO postgres;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Data for Name: api_alternative; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_alternative (id, title, image, is_correct, "order", question_id) FROM stdin;
44	CHARLY GARCÍA	alternatives/cabcdfc590e74f909e8ce4e8a2d80747.png	t	3	14
45	VIETNAM	alternatives/8d6a79360a0a49428c4974080f759712.png	f	1	15
47	JAPÓN	alternatives/6691cfb64fd14b2888631a7cf34a78f3.png	f	3	15
46	MALI	alternatives/d273f9c6b0dd433196a0266773266423.png	t	2	15
4	LUCAS ASSADI	alternatives/4b4dd10e3f824c369556e89dbf79f1e7.png	f	3	1
48	HUEMUL	alternatives/655db748800f4f9c97ba1cf0a6d81989.png	f	1	16
5	LAIKA	alternatives/3c038d4bc68e49139774da23747cf1df.png	f	1	2
6	HACHIKO	alternatives/2b202c52630a4ad4915a9e8045f3a805.png	t	2	2
8	BELKA	alternatives/3a7b12a4e1ee493f953cafd72941852a.png	f	3	2
9	THOMAS EDISON	alternatives/743bdd2957864f588b5d71aa0b8002db.png	f	1	3
11	NIKOLA TESLA	alternatives/732fa9414c7940a6a25bcef926c5dca7.png	f	3	3
10	CHARLES DARWIN	alternatives/acef8533584646639ef12dd3c77d0f7a.png	t	2	3
12	LIMA	alternatives/b4c9a1ee1aa949a79060a5cc49474f61.png	f	1	4
14	MOSCÚ	alternatives/8abcf9796f694e8599d5a00f12b64ae2.png	f	3	4
13	ESTAMBUL	alternatives/24153250481343bb828627bd719b3793.png	t	2	4
15	MANUEL RODRÍGUEZ (2000)	alternatives/cb7aca11fa1f4cff8f4ec5e086207544.png	f	1	5
17	ARTURO PRAT (10000)	alternatives/93bf8f9c38644db89679954bac7b051a.png	f	3	5
16	LAUTARO	alternatives/929288d9785f47ccbf2c81356e0b64a0.png	t	2	5
19	ESCALADA DEPORTIVA	alternatives/d20e596e74ba42e5b1e5377f91655bf0.png	f	2	6
20	BREAKDANCE	alternatives/6712ffdd94494f27bd21086f900cb9e1.png	f	3	6
18	PÁDEL	alternatives/6771637e3e934945aa9249b89fb572b3.png	t	1	6
21	SATURNO	alternatives/ca16c9b3cf1641af8af7bd410a09fa85.png	f	1	7
22	VENUS	alternatives/912055a9af92440f8e3053cedb4c54a1.png	f	2	7
23	PLUTÓN	alternatives/992fae21789b411a85c3bc5398d4fd04.png	t	3	7
24	LÁPIZ PASTA	alternatives/6b238db23b164089856483dad17f4167.png	f	1	8
25	LA T DE COBRE	alternatives/759beda6a6f2418fbe70e96e38900743.png	f	2	8
26	BOMBA DE RACIMO	alternatives/2664abefd56f40a5a0041e0783cfecc7.png	t	3	8
27	FIEBRE DE BAILE	alternatives/78c21ba9cca24a7189ebb54ac516ddc5.png	f	1	9
28	PRIMER PLANO	alternatives/ce90ac57696c40018f20c988e314bbb7.png	f	2	9
29	CONTACTO	alternatives/25caea4c37bb497896b89a84ae1f8e19.png	t	3	9
30	TAJ MAHAL	alternatives/3dfbc44b4a004c289ba51332f1b8b5c0.png	f	1	10
31	CHICHEN ITZÁ	alternatives/306d7d41f19e4f04a6d3dede7b594101.png	f	2	10
34	NATALIA OREIRO	alternatives/71677177699b481d8ff3feb222a26ae0.png	f	2	11
35	KENITA LARRAÍN	alternatives/eec1a70e90144cd3a79781aa7fcf5616.png	f	3	11
33	ROCÍO MARENGO	alternatives/b2f9d4eda71b47cd99bc16d81e3b8e77.png	t	1	11
37	SCAR (El rey león)	alternatives/32090e28f8084381bfcc36130561cef7.png	f	2	12
38	ÚRSULA (La sirenita)	alternatives/0d2874af478a49eb8dff5caf95bf5a05.png	f	3	12
36	ALICIA (Alicia en el país de las maravillas)	alternatives/58f228e493854e109238abc92630094d.png	t	1	12
39	CLAUDIO BRAVO	alternatives/aaa24fb8b8624906a6ffe6734be66eae.png	f	1	13
41	ARTURO VIDAL	alternatives/d50e8758a2c1438ab48e992d004275d2.png	f	3	13
40	JORGE VALDIVIA	alternatives/f06fb3033fb94a5bb6343adb6fd7f1e0.png	t	2	13
42	GUSTAVO CERATI	alternatives/0941d2d402ae4775971da2e1db573618.png	f	1	14
43	ZETA BOSIO	alternatives/e4dfe2182f65492b8109671937569371.png	f	2	14
49	PUMA	alternatives/fe6229728ea946f48e6c0e8268165784.png	t	2	16
50	CÓNDOR	alternatives/220efdd55c924a858d0c5a32b5168531.png	f	3	16
51	JACK NICHOLSON	alternatives/c618179cacbd4693a742924dddd9e1c7.png	f	1	17
52	HEATH LEDGER	alternatives/894a3bb2c5b34dc2b23397ca263500d8.png	f	2	17
53	DANNY DEVITO	alternatives/9e2de76c49c54aaaaf9c3dc6b8b87bfd.png	t	3	17
54	SHAR PEI	alternatives/5186655ed97c4d37833d533f4dc2cf8a.png	f	1	18
55	CHOW CHOW	alternatives/f92c2505aff3447d952aaa8d8469360f.png	f	2	18
56	CHAP SUI	alternatives/980e1a8eeaae415c81463917a4ae5c16.png	t	3	18
57	BELUS PRAJOUX	alternatives/ff0e3f4082f64ecab1b58a8e7d3c57fe.png	f	1	19
58	GONZALO LAMA	alternatives/06211a8f1c614ee9bb6bf4b40c15e53f.png	f	2	19
59	MARIANO ZABALETA	alternatives/cd594602e2c440e98cf1814ee569acdd.png	t	3	19
61	ANÍBAL PINTO	alternatives/51963bd0c8364eb38b635ecd164fa859.png	f	2	20
62	JORGE ALESSANDRI	alternatives/482290b341824034b17c434694dc5b96.png	f	3	20
60	MANUEL BLANCO ENCALADA	alternatives/ce38454cfb304145a58b7f54a1b3c81c.png	t	1	20
63	LOS LEONES	alternatives/777b2c0f0c6d49c581d27737d42cfd96.png	f	1	21
65	BAQUEDANO	alternatives/f02de76bafe6452faf912080d594150a.png	f	3	21
64	SANTA LUCÍA	alternatives/1e61e6d8a7d842c4ab212e009c2a8a11.png	t	2	21
66	“EL CIGARRITO” (Foto Víctor Jara)	alternatives/12665a0575c04737a1d950858418a9dd.png	f	1	22
68	“FLASHBACK” (Foto Javiera Mena)	alternatives/67b405f81d0c4d009e1dc7851305fc14.png	f	3	22
67	“SOBREVIVIENDO” (Foto Víctor Heredia)	alternatives/b89f8a1a30884756b988e7588a93a877.png	t	2	22
70	JIMI HENDRIX	alternatives/f5ebed96fd7d423fbce17b6c63b6f591.png	f	2	23
71	JANIS JOPLIN	alternatives/9bf37c2fa4034f8eac018940bde26a2b.png	f	3	23
32	BASÍLICA DE LA SAGRADA FAMILIA	alternatives/6d85cced85e446b0ad188a18a0d6de80.png	t	3	10
69	JOHN LENNON	alternatives/7102b7dc66b643fb9c8ab49f0d8d5db1.png	t	1	23
73	BALLENA	alternatives/d40e4d2a0488486984f30159495335d0.png	f	2	24
74	MURCIÉLAGO	alternatives/19bd2837ade34ea9bc0a49efca0f2b24.png	f	3	24
72	MANTIS RELIGIOSA	alternatives/a37906bef9d347ed9d5a4bdbc86cece6.png	t	1	24
76	COMETÍN	alternatives/59f93a5c86f44ebf816e89383e66e075.png	f	2	25
77	ROBOTINA	alternatives/8c02e51225dc482aa3f2b3b42998636d.png	f	3	25
75	BENDER	alternatives/79767ec9f2cf4b0e8e71276953751fc7.png	t	1	25
78	DIANA SPENCER	alternatives/d114b4d52f8740ada4dbd936a440b5bb.png	f	1	26
79	KATE MIDDLETON	alternatives/64392f78e9cf422db18012253dd0034c.png	f	2	26
80	MEGHAN MARKLE	alternatives/8bcd9ae4e7c242489932f12aa5875dd2.png	t	3	26
82	UNIVERSIDAD CATÓLICA	alternatives/bde876fd0e284ab8ac795d840d441040.png	f	2	27
83	DEPORTES SANTA CRUZ	alternatives/a5c2b5f19c98438b8d6b89573cef7be9.png	f	3	27
81	HURACÁN	alternatives/55eb6a3732d54daab27662120ae1ebd7.png	t	1	27
84	CHARLIE SHEEN Y EMILIO ESTÉVEZ	alternatives/b5549e2bc359415e8e40ed50c15b1b13.png	f	1	28
86	PIMPINELA	alternatives/93f578a8660946eaa6e514dc899c3e79.png	f	3	28
85	MAGIC TWINS	alternatives/d3cda1276ce249d09afb58d138cb16f2.png	t	2	28
87	LOS TRES	alternatives/fe7e35a5712941f1ad7fb8e1a2f8e8a0.png	f	1	29
88	LA LEY	alternatives/63eb01b9a9ad4837b757274b055c2adb.png	f	2	29
89	MOLOTOV	alternatives/0b32465ef6d64cc8b0a4f94f8e4943e7.png	t	3	29
90	MICHAEL JACKSON	alternatives/1808e3b489354f91a8d02357a0b5e63f.png	f	1	30
91	ADELE	alternatives/7a0b9e60604a43d2b4fde525aa0fb47f.png	t	2	30
92	BAD BUNNY	alternatives/8cc4162c6eee4fc8b4f611361ecd65aa.png	f	3	30
93	LUNA	alternatives/0b9653d6b20848d48916d54a9e0d889a.png	f	1	31
94	JÚPITER	alternatives/23bba7654139468b9cbecc54e9b52dbb.png	t	2	31
95	TITÁN	alternatives/1877539f14614f4cba76f019a34d47b8.png	f	3	31
96	HUMBERTO SUAZO	alternatives/45d71dae6a0844b0b3ad574363480e56.png	f	1	32
97	JAVIER MARGAS	alternatives/44a305daddef49bab50c9e1d473b40ef.png	f	2	32
98	MARK GONZÁLEZ	alternatives/4a4a385865884fa3b9ec9abe57b7084f.png	t	3	32
100	ENTREPIERNAS	alternatives/3da275b8dc8b4cb09bd40a936571f951.png	f	2	33
101	CHIGUALOCO	alternatives/9522f3b6451c460b8eaaf40279b2abda.png	f	3	33
99	SACACHISPAS	alternatives/614cbf35e9e147509d37c9ffde22539d.png	t	1	33
102	LUIS MIGUEL	alternatives/a785cf31d3654c389b0fefceb513b665.png	f	1	34
103	MYRIAM HERNÁNDEZ	alternatives/2dcf82d120754b7195230e70b789ab88.png	f	2	34
104	MIGUEL BOSÉ	alternatives/0ae66a94983a4f3cb0e1300a69e2fe63.png	t	3	34
106	E.T.	alternatives/d077d65e782f473bb6446f36d9c7b03b.png	f	2	35
107	JURASSIC PARK	alternatives/ebbf02f6fb27442ab76c96f552a10f8c.png	f	3	35
105	TITANIC	alternatives/189ef80a564d449881b815a95f65fed8.png	t	1	35
108	FELIPE VI	alternatives/efafa6ede3c24031be20d1305cc4caa4.png	f	1	36
110	LUIS I	alternatives/d06cd4d4be3a4df08b1f72c1815e1135.png	f	3	36
109	LEÓN XIV	alternatives/bd5d0213d175465ebae45f50d40051c5.png	t	2	36
111	MALUMA	alternatives/0ff017eed2744cfca46b3d69fc66acf3.png	f	1	37
112	SHAKIRA	alternatives/6b1a5867910e42ce88484ffe1b9be2fb.png	f	2	37
113	LUIS FONSI	alternatives/46981f6f39604386b480a4fad7c4c447.png	t	3	37
114	GEMINI	alternatives/bc46b885c5b34b67b11a61589b8e752d.png	f	1	38
115	CLAUDE	alternatives/e96869c18d4b446eac739b7e379bc46f.png	f	2	38
116	NAPSTER	alternatives/3c5986794b4f467ea95e85ebc5714d61.png	t	3	38
117	SANCHO PANZA	alternatives/7f0ff73b81d84db5ad8c4915186e99b4.png	f	1	39
118	DULCINEA	alternatives/9e4462a5a0e74e29a1cb58ab1078ca2a.png	f	2	39
119	ROMEO MONTESCO	alternatives/1ce94efb8fe247a7af6e5bb5c7904f9a.png	t	3	39
120	LADY GAGA – STEFANI GERMANOTTA	alternatives/9538c2cc75584fcc90009580793f7ced.png	f	1	40
122	BRUNO MARS – PETER HERNÁNDEZ	alternatives/10f1d3e3d6f64de098800b4e87c8db1a.png	f	2	40
121	DADDY YANKEE – JOSÉ OSORIO	alternatives/ce53f1296ece46ad8c3b5a24cc163b12.png	t	3	40
123	GUYANA	alternatives/1c66c947b5c1450abb93e6a82d5962ba.png	t	1	41
124	EL CONGO	alternatives/3b0f45c3e34545299220f7fc97946e52.png	f	2	41
125	LESOTHO	alternatives/b6dc47f7f5b449a5accb65935eeb841f.png	f	3	41
126	EL TRAUCO	alternatives/d8b7d0e38806441f87a7c8030e69ecd0.png	f	1	42
127	LA PINCOYA	alternatives/44df142ff55d4ca28054cb3e43e1aa1d.png	f	2	42
128	AKU AKU (Rapa Nui)	alternatives/72539572021342c78b536a6f6090cb42.png	t	3	42
130	NICOLÁS MASSÚ	alternatives/28287ab00a4046e1bfae27f0d0c47fc1.png	f	2	43
131	HANS GILDEMEISTER	alternatives/c88bbd389a4347908693e9c8b2ca86f9.png	f	3	43
129	ALEJANDRO TABILO	alternatives/46e727bd89264103875b69ac4ae00fa5.png	t	1	43
132	NEIL ARMSTRONG	alternatives/e1e7b9a3a22a4f38955c175e641e0ae6.png	f	1	44
133	MICHAEL COLLINS	alternatives/4c175f8e24d6407681cd6317fc445959.png	t	2	44
134	BUZZ ALDRIN	alternatives/de9737dfa30340d9b72ffb3360494488.png	f	3	44
135	LOS BÚNKERS	alternatives/b747bee7f61b447b9329142a41e6c7ab.png	f	1	45
137	LOS BLOPS	alternatives/8ccd2ff6a5bb473a8187ceb8eeaec117.png	f	3	45
136	EL CUARTETO DE NOS	alternatives/f369e2d1abfb451b9d71399ebbc93087.png	t	2	45
138	JOHN F. KENNEDY	alternatives/7c0d8b6fec3c49218fc5ab4e60ddbd86.png	f	1	46
139	JIMMY CARTER	alternatives/1155833550214903ab6ecaf7f49108b3.png	t	2	46
140	ABRAHAM LINCOLN	alternatives/d1a5c7d6327848a5b46647a1e026fcbc.png	f	3	46
141	REESE WITHERSPOON	alternatives/fe2133b19338474ba6e4bfbfee3af112.png	f	1	47
142	SALMA HAYEK	alternatives/8a454d0c4a5f47deabc58a435de41595.png	f	2	47
143	TAYLOR SWIFT	alternatives/9b897dd5172a4c178279fe551d1f3514.png	t	3	47
144	ARAUCARIA	alternatives/9212374b071143e8ba7ad6f130f7341a.png	f	1	48
145	CANELO	alternatives/4e38b08ad92c4ebabfc76ec0672c976c.png	f	2	48
146	BAOBAB	alternatives/e74a1a925bf9489c9f42d47af456dadf.png	t	3	48
147	MI BELLA GENIO	alternatives/82552493470048adaf68a2c09c4f23ec.png	f	1	49
148	HECHIZADA	alternatives/92ecfdc8dc46422c908d90038e2d676f.png	f	2	49
149	LOS AÑOS DORADOS	alternatives/0b525375260248328c76818ef86ffe3d.png	t	3	49
150	YEN	alternatives/fcc674b037bd4525b32b7550e33c254c.png	f	1	50
152	QUETZAL	alternatives/35a05262c4194dcdbbc344a52d0d31d0.png	f	3	50
151	RUS	alternatives/e243a9bf5fd24b50b05f6e0cd08ca385.png	t	2	50
154	ANTONIO VODANOVIC	alternatives/30f9d9e6d5794cbc89654845b4750c32.png	f	2	51
155	CÉSAR ANTONIO SANTIS	alternatives/11c87cb02e92407abd2a97f08a9461fe.png	f	3	51
153	JUAN GUILLERMO VIVADO	alternatives/530f0b3807124be88cf2d01250cc2fd0.png	t	1	51
157	JOE COCKER	alternatives/de99b828adcc42119ada4acc1cc864c6.png	f	2	52
158	AXL ROSE	alternatives/7175ded42b3f46faa5cc6f767544fe04.png	f	3	52
156	DEAN MARTIN	alternatives/9d0e0c08368347679be5029070e43d52.png	t	1	52
159	AZUL	alternatives/c32cd2ed4c21478ab81d4432621685da.png	f	1	53
160	NARANJA	alternatives/c63ecd90aadb4a6ab91340bfbbb4b3cf.png	t	2	53
161	AMARILLO	alternatives/3d61f87f5340469abf58e8b9ae398fe6.png	f	3	53
163	DILMA ROUSSEF	alternatives/91283ee0c6a54aa5b6f6320d94fcebdd.png	f	2	54
164	TANCREDO NEVES	alternatives/fdceeb887e7d4c64913b105fd90e06f4.png	f	3	54
162	JOAO HAVELANGE	alternatives/9acd1de7ff6746efa1bff39cced95acb.png	t	1	54
165	LUJURIA	alternatives/9badc41a6e0c493f829c8b6141ba1f20.png	f	1	55
166	DEPRESIÓN	alternatives/1370b1a376d84f0dab131aa9b6669b2b.png	t	2	55
167	PEREZA	alternatives/0ce9b85a8ead47cf8e86640962d52d12.png	f	3	55
168	JUAN ALCAYAGA	alternatives/7ac826bda96f4d03a436520b6930491f.png	f	1	56
170	JULIO MILOSTICH	alternatives/5e8d0d08e836406e868d418eb90faa2b.png	f	3	56
169	GABRIEL BORIC	alternatives/cbae17517593495f97129ac4a2cfff28.png	t	2	56
171	MONUMENTAL	alternatives/c008312e008047218d5ab38b4371c8ac.png	f	1	57
172	SÁNCHEZ RUMOROSO	alternatives/f606d43e342943ce9dfeb57bee1f2a36.png	f	2	57
173	SÁNCHEZ PIZJUAN	alternatives/82a6230a7bb548cba8c7e12deba35b3e.png	t	3	57
174	MICHAEL SCHUMACHER	alternatives/427c336f4c964d05ba3922633689e56c.png	f	1	58
176	LEWIS HAMILTON	alternatives/3bcfb5cfaddc44d78d4a0bc408942c8a.png	f	3	58
175	TONY HAWK	alternatives/e95b6d895ae9400da892f220b9bd8e2a.png	t	2	58
177	ROCKY	alternatives/074c750298974849928ea30c837af008.png	f	1	59
179	COBRA	alternatives/0c80d22469e44acda7eaf487b4e43739.png	f	3	59
178	ATRACCIÓN FATAL	alternatives/ba61ef71fbe44992b63aabfcff961a55.png	t	2	59
180	ANDREA BOCELLI	alternatives/6d219d102e2f42d79d64143cb2698db3.png	f	1	60
186	MATT DAMON	alternatives/9988d97cf3fa4a62913d17e2e3c2c3ad.png	f	1	62
187	ZAC EFRON	alternatives/e5635f285b0e41b489900168050c47b0.png	f	2	62
181	ROY ORBISON	alternatives/d4bb39b023c846d0bbbeb422ca7aee02.png	t	2	60
182	STEVIE WONDER	alternatives/c28f3026e2c34274b0ecaf0f27204ecc.png	f	3	60
1	RAFA MÁRQUEZ	alternatives/3de5f6ab967d47ad88519659a197d62b.png	t	1	1
188	TAYLOR FRITZ	alternatives/cb8f7b3be60c48f194a66e23f3fd2186.png	t	3	62
190	CURACAVÍ	alternatives/cabfe5515fba4f1cb30253912350bc3c.png	f	2	63
191	PEÑAFLOR	alternatives/37af3af04626408683ecb3f09b7cdf93.png	f	3	63
189	MACHALÍ	alternatives/081ace7e300d4c568b043f9b3b0e320a.png	t	1	63
193	PETAURO DEL AZÚCAR	alternatives/325034b3f25d4c9b97c4dfff126e9756.png	f	2	64
194	SERVAL	alternatives/f955d7329a074d8abdf4b8f0afe7d198.png	f	3	64
192	PULPO	alternatives/305539ceb1854a5cb1b9b6579c7295ab.png	t	1	64
195	CEREZA	alternatives/3dcf8295863a469a9890ec1b534c9ad8.png	t	1	61
196	MANGO	alternatives/fddf5ab9210b49da80dca11c1aa58e17.png	f	2	61
197	PIÑA	alternatives/ea879a09c43f4b1fbff446c575875fa0.png	f	3	61
2	RAFAEL OLARRA	alternatives/4684424b7bab47c3ba250a224d2d8106.png	f	2	1
\.


--
-- Data for Name: api_gamesession; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_gamesession (id, name, is_active, created_at, current_player_session_id, alternatives_status, gc_question_status) FROM stdin;
1	Programa #70 - El Impostor	f	2026-08-10 02:56:27.630617+00	2	f	f
2	Programa #70 - El Impostor	t	2026-08-11 17:34:06.805421+00	3	f	f
\.


--
-- Data for Name: api_player; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_player (id, name, status, created_at, "order", description) FROM stdin;
2	Guillermo Champin	active	2026-08-10 02:55:53.046827+00	1	Equipo 2 Programa 08 de Agosto
1	Soledad Parizzi	active	2026-08-10 02:55:29.61653+00	1	Equipo 1 Programa 08 de Agosto
\.


--
-- Data for Name: api_playerquestionanswer; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_playerquestionanswer (id, status, answered_at, selected_alternative_id, player_session_id, question_id) FROM stdin;
1	pending	\N	\N	1	1
2	pending	\N	\N	1	2
3	pending	\N	\N	1	3
4	pending	\N	\N	1	4
5	pending	\N	\N	1	5
6	pending	\N	\N	1	6
7	pending	\N	\N	1	7
8	pending	\N	\N	1	8
9	pending	\N	\N	1	9
10	pending	\N	\N	1	10
11	pending	\N	\N	1	11
12	pending	\N	\N	1	12
13	pending	\N	\N	1	13
14	pending	\N	\N	1	14
15	pending	\N	\N	1	15
16	pending	\N	\N	1	16
17	pending	\N	\N	1	17
18	pending	\N	\N	1	18
19	pending	\N	\N	1	19
20	pending	\N	\N	1	20
21	pending	\N	\N	1	21
22	pending	\N	\N	1	22
23	pending	\N	\N	1	23
24	pending	\N	\N	1	24
25	pending	\N	\N	1	25
26	pending	\N	\N	1	26
27	pending	\N	\N	1	27
28	pending	\N	\N	1	28
29	pending	\N	\N	1	29
30	pending	\N	\N	1	30
31	pending	\N	\N	2	31
32	pending	\N	\N	2	32
33	pending	\N	\N	2	33
35	pending	\N	\N	2	35
34	pending	\N	\N	2	34
39	pending	\N	\N	2	39
40	pending	\N	\N	2	40
41	pending	\N	\N	2	41
42	pending	\N	\N	2	42
43	pending	\N	\N	2	43
44	pending	\N	\N	2	44
45	pending	\N	\N	2	45
46	pending	\N	\N	2	46
47	pending	\N	\N	2	47
48	pending	\N	\N	2	48
49	pending	\N	\N	2	49
50	pending	\N	\N	2	50
51	pending	\N	\N	2	51
61	incorrect	2026-08-11 17:37:59.301048+00	4	3	1
52	pending	\N	\N	2	52
53	pending	\N	\N	2	53
54	pending	\N	\N	2	54
55	pending	\N	\N	2	55
56	pending	\N	\N	2	56
57	pending	\N	\N	2	57
58	pending	\N	\N	2	58
59	pending	\N	\N	2	59
60	pending	\N	\N	2	60
38	pending	\N	\N	2	38
36	pending	\N	\N	2	36
37	pending	\N	\N	2	37
62	pending	\N	\N	3	2
63	pending	\N	\N	3	3
64	pending	\N	\N	3	4
65	pending	\N	\N	3	5
66	pending	\N	\N	3	6
67	pending	\N	\N	3	7
68	pending	\N	\N	3	8
69	pending	\N	\N	3	9
70	pending	\N	\N	3	10
71	pending	\N	\N	3	11
72	pending	\N	\N	3	12
73	pending	\N	\N	3	13
74	pending	\N	\N	3	14
75	pending	\N	\N	3	15
76	pending	\N	\N	3	16
77	pending	\N	\N	3	17
78	pending	\N	\N	3	18
79	pending	\N	\N	3	19
80	pending	\N	\N	3	20
81	pending	\N	\N	3	21
82	pending	\N	\N	3	22
83	pending	\N	\N	3	23
84	pending	\N	\N	3	24
85	pending	\N	\N	3	25
86	pending	\N	\N	3	26
87	pending	\N	\N	3	27
88	pending	\N	\N	3	28
89	pending	\N	\N	3	29
90	pending	\N	\N	3	30
91	pending	\N	\N	4	31
92	pending	\N	\N	4	32
93	pending	\N	\N	4	33
94	pending	\N	\N	4	34
95	pending	\N	\N	4	35
96	pending	\N	\N	4	36
97	pending	\N	\N	4	37
98	pending	\N	\N	4	38
99	pending	\N	\N	4	39
100	pending	\N	\N	4	40
101	pending	\N	\N	4	41
102	pending	\N	\N	4	42
103	pending	\N	\N	4	43
104	pending	\N	\N	4	44
105	pending	\N	\N	4	45
106	pending	\N	\N	4	46
107	pending	\N	\N	4	47
108	pending	\N	\N	4	48
109	pending	\N	\N	4	49
110	pending	\N	\N	4	50
111	pending	\N	\N	4	51
112	pending	\N	\N	4	52
113	pending	\N	\N	4	53
114	pending	\N	\N	4	54
115	pending	\N	\N	4	55
116	pending	\N	\N	4	56
117	pending	\N	\N	4	57
118	pending	\N	\N	4	58
119	pending	\N	\N	4	59
120	pending	\N	\N	4	60
\.


--
-- Data for Name: api_playersession; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_playersession (id, time_limit_seconds, accumulated_seconds, timer_status, last_timer_start, current_question_index, "order", game_session_id, player_id, question_group_id, alternative_text_visibility) FROM stdin;
1	180	0	stopped	\N	1	1	1	1	1	f
2	60	0	stopped	\N	1	2	1	2	2	f
4	60	56	paused	\N	1	2	2	2	2	f
3	60	60	stopped	\N	2	1	2	1	1	f
\.


--
-- Data for Name: api_question; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_question (id, question_text, "order", question_group_id, difficulty) FROM stdin;
1	1.\tFUTBOLISTAS CHILENOS (F)	1	1	easy
2	2.\tPERROS QUE ORBITARON LA TIERRA (M)	2	1	medium
3	3.\tGRANDES INVENTORES DE LA HISTORIA	3	1	easy
4	4.\tCIUDADES QUE SON CAPITALES	4	1	medium
5	5.\tAPARECEN EN BILLETES CHILENOS	5	1	easy
6	6.\tDEPORTES OLÍMPICOS	6	1	medium
7	7.\tPLANETAS DEL SISTEMA SOLAR	7	1	easy
8	8.\tINVENTOS CHILENOS	8	1	medium
9	9.\tPROGRAMAS DE CHILEVISIÓN	9	1	easy
10	10. MARAVILLAS DEL MUNDO MODERNO	10	1	hard
11	11. REINAS DEL FESTIVAL DE VIÑA DEL MAR	11	1	medium
12	12. VILLANOS DE DISNEY	12	1	easy
13	13.\tFUTBOLISTAS NACIDOS EN CHILE	13	1	medium
14	14.\tINTEGRANTES DE SODA STEREO	14	1	easy
15	15.\tPAÍSES DE ASIA	15	1	medium
16	16.\tANIMALES QUE ESTÁN EN EL ESCUDO DE CHILE	16	1	easy
17	17.\tACTORES QUE HAN INTERPRETADO AL GUASÓN	17	1	medium
18	18.\tRAZAS DE PERROS	18	1	easy
19	19.\tTENISTAS CHILENOS	19	1	medium
20	20.\tPRESIDENTES DE CHILE QUE NACIERON EN SANTIAGO	20	1	hard
21	21.\tESTACIONES DE METRO CON COMBINACIÓN	21	1	easy
22	22.\tCANCIONES CHILENAS	22	1	medium
23	23.\tSE PRESENTARON EN EL FESTIVAL DE WOODSTOCK 1969	23	1	easy
31	1.\tSATÉLITES NATURALES	1	2	easy
32	2.\tFUTBOLISTAS NACIDOS EN CHILE	2	2	medium
33	3.\tPUEBLOS DE CHILE	3	2	easy
34	4.\tHAN GANADO GAVIOTA DE PLATINO EN EL FESTIVAL DE VIÑA DEL MAR	4	2	medium
35	5.\tPELÍCULAS DIRIGIDAS POR SPIELBERG	5	2	easy
36	6.\tREYES DE ESPAÑA	6	2	medium
37	7.\tCANTANTES COLOMBIANOS	7	2	easy
38	8.\tAPLICACIONES DE I.A	8	2	medium
39	9.\tPERSONAJES DE “DON QUIJOTE”	9	2	easy
40	10.\tNOMBRES REALES DE ARTISTAS	10	2	hard
41	PAÍSES DE ÁFRICA	11	2	medium
42	12.\tMITOLOGÍA CHILOTA	12	2	easy
43	13.\tTENISTAS NACIDOS EN CHILE	13	2	medium
44	14.\tASTRONAUTAS QUE PISARON LA LUNA	14	2	easy
45	15.\tGRUPOS MUSICALES CHILENOS	15	2	medium
46	16.\tPRESIDENTES DE ESTADOS UNIDOS QUE FUERON ASESINADOS	16	2	easy
47	17.\tMIDEN MENOS DE 1.60	17	2	medium
48	18.\tÁRBOLES NATIVOS DE CHILE	18	2	easy
49	19.\tSERIES DE TV DE LOS 60	19	2	medium
50	20.\tMONEDAS DEL MUNDO	20	2	hard
51	21.\tANIMADORES DEL FESTIVAL DE VIÑA	21	2	easy
52	22.\tMÚSICOS ROCKEROS	22	2	medium
53	23.\tCOLORES PRIMARIOS	23	2	easy
54	24.\tPRESIDENTES DE BRASIL	24	2	medium
55	25.\tPECADOS CAPITALES	25	2	easy
56	26.\tNACIERON EN PUNTA ARENAS	26	2	medium
57	27.\tESTADIOS CHILENOS	27	2	easy
58	28.\tPILOTOS FÓRMULA 1	28	2	medium
59	29.\tPELÍCULAS DE STALLONE	29	2	easy
60	30.\tMÚSICOS NO VIDENTES	30	2	medium
62	2.\tACTORES DE CINE	2	3	medium
63	3.\tCOMUNAS DE LA REGIÓN METROPOLITANA	3	3	easy
64	4.\tANIMALES EXÓTICOS	4	3	medium
61	1.\tFRUTAS TROPICALES	1	3	easy
24	24.\tANIMALES MAMÍFEROS	24	1	medium
25	25.\tPERSONAJES DE LA SERIE ANIMADA “LOS SUPERSÓNICOS”	25	1	easy
26	26.\tPRINCESAS DE GALES	26	1	medium
27	27.\tCLUBES DE FÚTBOL CHILENOS	27	1	easy
28	28.\tHERMANOS FAMOSOS	28	1	medium
29	29.\tGRUPOS MUSICALES CHILENOS	29	1	easy
30	30.\tSE HAN PRESENTADO EN EL SUPERBOWL (M)	30	1	medium
\.


--
-- Data for Name: api_questiongroup; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.api_questiongroup (id, name, description, created_at, "order") FROM stdin;
1	JUEGO FINAL EQUIPO 1	JUEGO FINAL EQUIPO 1	2026-08-07 23:04:13.772372+00	1
2	JUEGO FINAL EQUIPO 2	JUEGO FINAL EQUIPO 2	2026-08-10 02:21:37.575145+00	1
3	PRUEBA JUEGO	PRUEBA JUEGO	2026-08-10 02:51:07.796935+00	1
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add Token	7	add_token
26	Can change Token	7	change_token
27	Can delete Token	7	delete_token
28	Can view Token	7	view_token
29	Can add Token	8	add_tokenproxy
30	Can change Token	8	change_tokenproxy
31	Can delete Token	8	delete_tokenproxy
32	Can view Token	8	view_tokenproxy
33	Can add alternative	9	add_alternative
34	Can change alternative	9	change_alternative
35	Can delete alternative	9	delete_alternative
36	Can view alternative	9	view_alternative
37	Can add game session	10	add_gamesession
38	Can change game session	10	change_gamesession
39	Can delete game session	10	delete_gamesession
40	Can view game session	10	view_gamesession
41	Can add player	11	add_player
42	Can change player	11	change_player
43	Can delete player	11	delete_player
44	Can view player	11	view_player
45	Can add question	12	add_question
46	Can change question	12	change_question
47	Can delete question	12	delete_question
48	Can view question	12	view_question
49	Can add question group	13	add_questiongroup
50	Can change question group	13	change_questiongroup
51	Can delete question group	13	delete_questiongroup
52	Can view question group	13	view_questiongroup
53	Can add player session	14	add_playersession
54	Can change player session	14	change_playersession
55	Can delete player session	14	delete_playersession
56	Can view player session	14	view_playersession
57	Can add player question answer	15	add_playerquestionanswer
58	Can change player question answer	15	change_playerquestionanswer
59	Can delete player question answer	15	delete_playerquestionanswer
60	Can view player question answer	15	view_playerquestionanswer
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.authtoken_token (key, created, user_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	authtoken	token
8	authtoken	tokenproxy
9	api	alternative
10	api	gamesession
11	api	player
12	api	question
13	api	questiongroup
14	api	playersession
15	api	playerquestionanswer
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-08-07 23:02:20.287542+00
2	auth	0001_initial	2026-08-07 23:02:20.319136+00
3	admin	0001_initial	2026-08-07 23:02:20.330507+00
4	admin	0002_logentry_remove_auto_add	2026-08-07 23:02:20.333343+00
5	admin	0003_logentry_add_action_flag_choices	2026-08-07 23:02:20.336852+00
6	api	0001_initial	2026-08-07 23:02:20.372949+00
7	api	0002_alter_questiongroup_options_questiongroup_order	2026-08-07 23:02:20.376448+00
8	api	0003_alter_alternative_image	2026-08-07 23:02:20.378171+00
9	api	0004_question_difficulty	2026-08-07 23:02:20.380769+00
10	api	0005_alter_player_options_player_order	2026-08-07 23:02:20.383603+00
11	api	0006_player_description	2026-08-07 23:02:20.386571+00
12	api	0007_alter_gamesession_is_active_and_more	2026-08-07 23:02:20.421241+00
13	contenttypes	0002_remove_content_type_name	2026-08-07 23:02:20.430704+00
14	auth	0002_alter_permission_name_max_length	2026-08-07 23:02:20.434075+00
15	auth	0003_alter_user_email_max_length	2026-08-07 23:02:20.437504+00
16	auth	0004_alter_user_username_opts	2026-08-07 23:02:20.440325+00
17	auth	0005_alter_user_last_login_null	2026-08-07 23:02:20.44314+00
18	auth	0006_require_contenttypes_0002	2026-08-07 23:02:20.44369+00
19	auth	0007_alter_validators_add_error_messages	2026-08-07 23:02:20.44687+00
20	auth	0008_alter_user_username_max_length	2026-08-07 23:02:20.453206+00
21	auth	0009_alter_user_last_name_max_length	2026-08-07 23:02:20.474551+00
22	auth	0010_alter_group_name_max_length	2026-08-07 23:02:20.478947+00
23	auth	0011_update_proxy_permissions	2026-08-07 23:02:20.483456+00
24	auth	0012_alter_user_first_name_max_length	2026-08-07 23:02:20.48698+00
25	authtoken	0001_initial	2026-08-07 23:02:20.495976+00
26	authtoken	0002_auto_20160226_1747	2026-08-07 23:02:20.50682+00
27	authtoken	0003_tokenproxy	2026-08-07 23:02:20.507796+00
28	authtoken	0004_alter_tokenproxy_options	2026-08-07 23:02:20.509473+00
29	sessions	0001_initial	2026-08-07 23:02:20.514241+00
30	api	0008_gamesession_alternatives_status	2026-08-10 13:39:00.271469+00
31	api	0009_gamesession_gc_question_status	2026-08-10 13:39:00.275889+00
32	api	0010_playersession_alternative_text_visibility	2026-08-12 16:11:54.580237+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Name: api_alternative_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_alternative_id_seq', 197, true);


--
-- Name: api_gamesession_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_gamesession_id_seq', 2, true);


--
-- Name: api_player_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_player_id_seq', 2, true);


--
-- Name: api_playerquestionanswer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_playerquestionanswer_id_seq', 120, true);


--
-- Name: api_playersession_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_playersession_id_seq', 4, true);


--
-- Name: api_question_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_question_id_seq', 64, true);


--
-- Name: api_questiongroup_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.api_questiongroup_id_seq', 3, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 60, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, false);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 15, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 32, true);


--
-- Name: api_alternative api_alternative_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_alternative
    ADD CONSTRAINT api_alternative_pkey PRIMARY KEY (id);


--
-- Name: api_gamesession api_gamesession_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_gamesession
    ADD CONSTRAINT api_gamesession_pkey PRIMARY KEY (id);


--
-- Name: api_player api_player_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_player
    ADD CONSTRAINT api_player_pkey PRIMARY KEY (id);


--
-- Name: api_playerquestionanswer api_playerquestionanswer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_playerquestionanswer
    ADD CONSTRAINT api_playerquestionanswer_pkey PRIMARY KEY (id);


--
-- Name: api_playerquestionanswer api_playerquestionanswer_player_session_id_questi_fa8cb4f6_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_playerquestionanswer
    ADD CONSTRAINT api_playerquestionanswer_player_session_id_questi_fa8cb4f6_uniq UNIQUE (player_session_id, question_id);


--
-- Name: api_playersession api_playersession_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_playersession
    ADD CONSTRAINT api_playersession_pkey PRIMARY KEY (id);


--
-- Name: api_question api_question_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_question
    ADD CONSTRAINT api_question_pkey PRIMARY KEY (id);


--
-- Name: api_questiongroup api_questiongroup_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_questiongroup
    ADD CONSTRAINT api_questiongroup_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: api_alternative_question_id_0b34913a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_alternative_question_id_0b34913a ON public.api_alternative USING btree (question_id);


--
-- Name: api_gameses_is_acti_742a2f_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_gameses_is_acti_742a2f_idx ON public.api_gamesession USING btree (is_active);


--
-- Name: api_gamesession_current_player_session_id_b7114d36; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_gamesession_current_player_session_id_b7114d36 ON public.api_gamesession USING btree (current_player_session_id);


--
-- Name: api_gamesession_is_active_820bc658; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_gamesession_is_active_820bc658 ON public.api_gamesession USING btree (is_active);


--
-- Name: api_playerq_player__14435f_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_playerq_player__14435f_idx ON public.api_playerquestionanswer USING btree (player_session_id, status);


--
-- Name: api_playerq_player__891da5_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_playerq_player__891da5_idx ON public.api_playerquestionanswer USING btree (player_session_id, question_id);


--
-- Name: api_playerquestionanswer_player_session_id_6ea31ddb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_playerquestionanswer_player_session_id_6ea31ddb ON public.api_playerquestionanswer USING btree (player_session_id);


--
-- Name: api_playerquestionanswer_question_id_81218d81; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_playerquestionanswer_question_id_81218d81 ON public.api_playerquestionanswer USING btree (question_id);


--
-- Name: api_playerquestionanswer_selected_alternative_id_739be57c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_playerquestionanswer_selected_alternative_id_739be57c ON public.api_playerquestionanswer USING btree (selected_alternative_id);


--
-- Name: api_players_game_se_0120f9_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_players_game_se_0120f9_idx ON public.api_playersession USING btree (game_session_id, "order");


--
-- Name: api_playersession_game_session_id_4852dd35; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_playersession_game_session_id_4852dd35 ON public.api_playersession USING btree (game_session_id);


--
-- Name: api_playersession_player_id_5ee81d13; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_playersession_player_id_5ee81d13 ON public.api_playersession USING btree (player_id);


--
-- Name: api_playersession_question_group_id_4ebcb67d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_playersession_question_group_id_4ebcb67d ON public.api_playersession USING btree (question_group_id);


--
-- Name: api_question_question_group_id_9caa37e9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_question_question_group_id_9caa37e9 ON public.api_question USING btree (question_group_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: api_alternative api_alternative_question_id_0b34913a_fk_api_question_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_alternative
    ADD CONSTRAINT api_alternative_question_id_0b34913a_fk_api_question_id FOREIGN KEY (question_id) REFERENCES public.api_question(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_gamesession api_gamesession_current_player_sessi_b7114d36_fk_api_playe; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_gamesession
    ADD CONSTRAINT api_gamesession_current_player_sessi_b7114d36_fk_api_playe FOREIGN KEY (current_player_session_id) REFERENCES public.api_playersession(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_playerquestionanswer api_playerquestionan_player_session_id_6ea31ddb_fk_api_playe; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_playerquestionanswer
    ADD CONSTRAINT api_playerquestionan_player_session_id_6ea31ddb_fk_api_playe FOREIGN KEY (player_session_id) REFERENCES public.api_playersession(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_playerquestionanswer api_playerquestionan_question_id_81218d81_fk_api_quest; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_playerquestionanswer
    ADD CONSTRAINT api_playerquestionan_question_id_81218d81_fk_api_quest FOREIGN KEY (question_id) REFERENCES public.api_question(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_playerquestionanswer api_playerquestionan_selected_alternative_739be57c_fk_api_alter; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_playerquestionanswer
    ADD CONSTRAINT api_playerquestionan_selected_alternative_739be57c_fk_api_alter FOREIGN KEY (selected_alternative_id) REFERENCES public.api_alternative(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_playersession api_playersession_game_session_id_4852dd35_fk_api_games; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_playersession
    ADD CONSTRAINT api_playersession_game_session_id_4852dd35_fk_api_games FOREIGN KEY (game_session_id) REFERENCES public.api_gamesession(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_playersession api_playersession_player_id_5ee81d13_fk_api_player_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_playersession
    ADD CONSTRAINT api_playersession_player_id_5ee81d13_fk_api_player_id FOREIGN KEY (player_id) REFERENCES public.api_player(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_playersession api_playersession_question_group_id_4ebcb67d_fk_api_quest; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_playersession
    ADD CONSTRAINT api_playersession_question_group_id_4ebcb67d_fk_api_quest FOREIGN KEY (question_group_id) REFERENCES public.api_questiongroup(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_question api_question_question_group_id_9caa37e9_fk_api_questiongroup_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_question
    ADD CONSTRAINT api_question_question_group_id_9caa37e9_fk_api_questiongroup_id FOREIGN KEY (question_group_id) REFERENCES public.api_questiongroup(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict UK363JKU4FCQ9ahdDhS8d4z8y0VvybM1Fqo1oR01G1aDjaPUfplwMQQqndXsUbp

