# Generated by Django 5.2.6 on 2026-07-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questiongroup',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
