# Generated by Django 5.2.6 on 2026-07-25 19:35

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_questiongroup_options_questiongroup_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.alternative_image_upload_path),
        ),
    ]
