# Generated by Django 5.2.6 on 2026-07-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_alternative_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Baja'), ('medium', 'Media'), ('hard', 'Alta')], default='medium', max_length=20),
        ),
    ]
