# Generated by Django 5.2.6 on 2026-07-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_question_difficulty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='player',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
