# Generated by Django 5.2.6 on 2026-07-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_player_options_player_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
