# Generated by Django 5.2.6 on 2026-07-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_player_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterUniqueTogether(
            name='playerquestionanswer',
            unique_together={('player_session', 'question')},
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['is_active'], name='api_gameses_is_acti_742a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='playerquestionanswer',
            index=models.Index(fields=['player_session', 'status'], name='api_playerq_player__14435f_idx'),
        ),
        migrations.AddIndex(
            model_name='playerquestionanswer',
            index=models.Index(fields=['player_session', 'question'], name='api_playerq_player__891da5_idx'),
        ),
        migrations.AddIndex(
            model_name='playersession',
            index=models.Index(fields=['game_session', 'order'], name='api_players_game_se_0120f9_idx'),
        ),
    ]
