# Generated by Django 5.2.6 on 2026-08-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_gamesession_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='alternatives_status',
            field=models.BooleanField(default=True),
        ),
    ]
