# Generated by Django 5.2.6 on 2026-08-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_gamesession_alternatives_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='gc_question_status',
            field=models.BooleanField(default=True),
        ),
    ]
