# Generated by Django 5.2.6 on 2026-08-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_gamesession_gc_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersession',
            name='alternative_text_visibility',
            field=models.BooleanField(default=False),
        ),
    ]
