FROM arm64v8/python:3.13-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /
COPY ./requirements.txt .
RUN apt-get update && apt-get install -yy build-essential gcc && pip install --upgrade pip && pip install -r requirements.txt && pip install gunicorn gevent

WORKDIR /app
COPY . .

EXPOSE 80

# Run migrations and server at entrypoint
ENTRYPOINT ./docker/entrypoint.sh