server {
    listen 80;
    server_name _;

    # Frontend React
    root /usr/share/nginx/html;
    index index.html;

    # Route SPA
    location / {
        try_files $uri /index.html;
    }

    # API requests (Django)
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;

        # Optimization: Increase proxy buffers to prevent disk-buffering warnings for large history responses
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
    }

    # WebSocket requests (Django Channels)
    location /ws/ {
        proxy_pass http://backend:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Increase timeout for WebSocket connections
        proxy_read_timeout 3600;
    }

    # Media files (Django Storage)
    location /media/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
    }

}
